/*
 * \brief  Spunky initialization before the first call to Ada code
 * \author Martin Stein
 * \date   2019-12-19
 */

/*
 * Copyright (C) 2019 Genode Labs GmbH
 *
 * This file is part of the Genode OS framework, which is distributed
 * under the terms of the GNU Affero General Public License version 3.
 */

/* base-hw includes */
#include <kernel/ada_interfacing.h>
#include <kernel/signal_receiver.h>
#include <kernel/ipc_node.h>
#include <kernel/cpu_scheduler.h>
#include <kernel/timer.h>
#include <kernel/lock.h>
#include <kernel/main.h>
#include <kernel/thread.h>
#include <kernel/inter_processor_work.h>
#include <pic.h>
#include <cpu.h>
#include <platform.h>
#include <hw/spec/x86_64/x86_64.h>

using namespace Kernel;

/**
 * This fuinction references the likewise-named sub-program in the Ada main
 * package generated by the GNAT binder for the core-spunky-pc library
 * (see '$(BUILD_DIR)/var/libcache/core-spunky-pc/b~core_spunky_pc.adb').
 */
extern "C" void core_spunky_pc_init();

void Kernel::main_initialize_spunky()
{
	core_spunky_pc_init();

	Ipc_node::assert_types_have_same_size();
	Signal_handler::assert_types_have_same_size();
	Signal_context_killer::assert_types_have_same_size();
	Signal_context::assert_types_have_same_size();
	Signal_receiver::assert_types_have_same_size();
	Cpu_share::assert_types_have_same_size();
	Cpu_scheduler::assert_types_have_same_size();
	Timer::assert_types_have_same_size();
	Timeout::assert_types_have_same_size();
	Board::Pic::assert_types_have_same_size();
	Board::Global_interrupt_controller::assert_types_have_same_size();
	Genode::Cpu::assert_types_have_same_size();
	Genode::Cpu::Context::assert_types_have_same_size();
	Genode::Cpu::Mmu_context::assert_types_have_same_size();
	Lock::assert_types_have_same_size();
}

addr_t lapic_virt_address()
{
	return
		Genode::Platform::mmio_to_virt(
			Hw::Cpu_memory_map::lapic_phys_base());
}

void thread_destruct(Genode::Kernel_object<Thread> &thread)
{
	thread.destruct();
}
