#
# \brief   Emulation of the verilog design 'monitor'
# \author  Automatically generated by 'tool/verilate'
# \date    2012-08-06
#

# set the program name
TARGET = monitor

# add C++ sources
SRC_CC += wishbone_slave.cc

# add simulation objects generated by 'verilator'
EXT_OBJECTS += $(PRG_DIR)/verilated.o $(PRG_DIR)/Vmonitor__ALL.a

# add library dependencies
LIBS += verilator_env_wb

