if {[have_spec foc] || [have_spec linux] || [have_board rpi3] ||
    [have_board imx53_qsb_tz]} {
	puts "Run script is not supported on this platform."
	exit 0
}

if {[get_cmd_switch --autopilot] && [have_board riscv_qemu]} {
	puts "Autopilot mode is not supported on this platform."
	exit 0
}

set on_hardware [expr ![have_include power_on/qemu]]

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_nic_pkg] \
                  [depot_user]/src/init \
                  [depot_user]/src/nic_bridge \
                  [depot_user]/src/nic_router \

build { app/ping server/nic_dump }

proc good_dst_ip { } {
	if {![have_include power_on/qemu]} {
		return "10.0.0.2"
	} else {
		return "10.0.2.2"
	}
}
proc bad_dst_port { } { return "12345" }
proc bad_dst_ip   { } { return "10.0.1.2" }

append config {

<config>

	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="platform_drv" caps="150">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Platform"/> </provides>
		<config>
			<device name="fec" type="fsl,imx6q-fec">
				<io_mem   address="0x2188000" size="0x4000"/>
				<irq      number="150"/>
				<irq      number="151"/>
				<property name="mii"        value="rgmii"/>
			</device>
			<policy label="nic_drv -> " info="yes"> <device name="fec"/> </policy>
		</config>
		<route>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nic_drv" caps="130">
		<binary name="fec_nic_drv"/>
		<resource name="RAM" quantum="20M"/>
		<config mode="uplink_client"/>
		<route>
			<service name="Uplink"> <child name="nic_router"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Platform"> <child name="platform_drv"/> </service>
			<service name="ROM">   <parent/> </service>
			<service name="PD">    <parent/> </service>
			<service name="RM">    <parent/> </service>
			<service name="CPU">   <parent/> </service>
			<service name="LOG">   <parent/> </service>
		</route>
	</start>

	<start name="nic_router" caps="200">
		<binary name="nic_router"/>
		<resource name="RAM" quantum="10M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes" verbose_packets="yes" verbose_packet_drop="yes" verbose="yes" dhcp_discover_timeout_sec="1">

			<policy label_prefix="nic_drv" domain="uplink"/>

			<domain name="uplink"/>

		</config>
	</start>

</config> }

install_config $config
build_boot_image { ping nic_dump }

append qemu_args " -nographic "
append_qemu_nic_args

set done_string ""
for {set i 0} {$i < 3} {incr i 1} {
	append done_string ".*child \"ping...\" exited with exit value 0.*\n"
}
append done_string ".*ping_22\] From 10.0.4.1 icmp_seq=.* Destination Unreachable.*\n"

append_if $on_hardware done_string ".*ping_23\] From [good_dst_ip] Destination Unreachable.*\n"

run_genode_until $done_string 30
