assert_spec x86_64

source ${genode_dir}/repos/dde_linux/run/wireguard.inc

#
# Overwrite exit procedure in order to always undo the host setup for Wireguard
#
rename exit run_tool_exit
proc exit {{status 0}} {

	wireguard_exit
	run_tool_exit $status
}

wireguard_start

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_nic_pkg] \
                  [depot_user]/src/init \
                  [depot_user]/src/nic_router

install_config {
<config verbose="yes" prio_levels="2">
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="drivers" caps="1000" managing_system="yes" priority="-1">
		<resource name="RAM" quantum="32M"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Uplink"> <child name="nic_router"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nic_router" caps="200">
		<resource name="RAM" quantum="10M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes"
		        dhcp_discover_timeout_sec="1">

			<!--<policy label_prefix="test-lwip_httpsrv" domain="downlink"/>-->
			<policy label_prefix="drivers"           domain="uplink"/>

			<domain name="uplink">

				<nat domain="downlink"
				     tcp-ports="16384"
				     udp-ports="16384"
				     icmp-ids="16384"/>

				<udp-forward port="55552" domain="downlink" to="10.0.3.2"/>

			</domain>

			<domain name="downlink" interface="10.0.3.1/24">

				<tcp dst="0.0.0.0/0"><permit-any domain="uplink" /></tcp>
				<udp dst="0.0.0.0/0"><permit-any domain="uplink" /></udp>
				<icmp dst="0.0.0.0/0" domain="uplink"/>

			</domain>

		</config>
	</start>

	<!-- platform driver only needed for memory allocation -->
	<start name="platform_drv">
		<resource name="RAM" quantum="32M"/>
		<provides> <service name="Platform"/> </provides>
		<route>
			<any-service> <parent/> </any-service>
		</route>
		<config> <policy label="wireguard -> "/> </config>
	</start>

	<start name="wireguard">
		<resource name="RAM" quantum="10M"/>
		<route>
			<service name="Timer">    <child name="timer"/> </service>
			<service name="Nic">      <child name="nic_router"/> </service>
			<service name="Platform"> <child name="platform_drv"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>
</config>
}

build { app/wireguard }

build_boot_image { wireguard }

append qemu_args "  -nographic"

run_genode_until forever
