assert_spec x86_64

source ${genode_dir}/repos/dde_linux/run/wireguard.inc

#
# Overwrite exit procedure in order to always undo the host setup for Wireguard
#
rename exit run_tool_exit
proc exit {{status 0}} {

	wireguard_exit
	run_tool_exit $status
}

wireguard_start

create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_nic_pkg] \
                  [depot_user]/src/init \
                  [depot_user]/src/nic_router

install_config {
<config verbose="yes" prio_levels="2">
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="drivers" caps="1000" managing_system="yes" priority="-1">
		<resource name="RAM" quantum="32M"/>
		<binary name="init"/>
		<route>
			<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Uplink"> <child name="nic_router"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="nic_router" caps="200">
		<resource name="RAM" quantum="10M"/>
		<provides>
			<service name="Nic"/>
			<service name="Uplink"/>
		</provides>
		<config verbose_domain_state="yes"
		        dhcp_discover_timeout_sec="1">

			<policy label_prefix="drivers"      domain="uplink"/>
			<policy label="wireguard -> down"   domain="wg_down"/>
			<policy label="wireguard -> uplink" domain="wg_up"/>
			<default-policy                     domain="downlink"/>

			<domain name="uplink">
				<nat domain="wg_down" tcp-ports="16384" udp-ports="16384" icmp-ids="16384"/>

				<udp-forward port="49002" domain="wg_down" to="10.0.3.2"/>
			</domain>

			<domain name="wg_down" interface="10.0.3.1/24">
				<udp dst="10.0.2.2/24"><permit port="49001" domain="uplink"/></udp>
			</domain>

			<domain name="wg_up" interface="10.1.1.1/24">
				<nat domain="downlink" tcp-ports="16384" udp-ports="16384" icmp-ids="16384"/>
			</domain>

			<domain name="downlink" interface="10.1.2.1/24">
				<dhcp-server ip_first="10.1.2.2"
				             ip_last="10.1.2.100"
				             dns_config_from="uplink"/>
				<tcp dst="0.0.0.0/0"><permit-any domain="wg_up" /></tcp>
				<udp dst="0.0.0.0/0"><permit-any domain="wg_up" /></udp>
				<icmp dst="0.0.0.0/0" domain="wg_up"/>
			</domain>
		</config>
	</start>

	<!-- platform driver only needed for memory allocation -->
	<start name="platform_drv">
		<resource name="RAM" quantum="32M"/>
		<provides> <service name="Platform"/> </provides>
		<route>
			<any-service> <parent/> </any-service>
		</route>
		<config> <policy label="wireguard -> "/> </config>
	</start>

	<start name="wireguard" caps="200">
		<resource name="RAM" quantum="10M"/>
		<config>
			<iface listen_port="49002" private_key="8GRSQZMgG1uuvz4APIBqrDmiLj8L886r++hzixjjHFc=">
				<peer public_key="r1Gslnm82X8NaijsWzPoSFzDZGl2tTJoPa+EJL4gYQw="
				      ip="10.0.2.2" port="49001" allowed_ip="10.0.9.1/32">
				</peer>
			</iface>
			</config>
		<route>
			<service name="Timer">    <child name="timer"/> </service>
			<service name="Nic">      <child name="nic_router"/> </service>
			<service name="Uplink">   <child name="nic_router"/> </service>
			<service name="Platform"> <child name="platform_drv"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>
</config>
}

build { app/wireguard }

build_boot_image { wireguard }

proc board_qemu_args { } {
	return " -nographic -machine q35 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -net nic,model=e1000,netdev=net0 "
}

run_genode_until forever
