#
# Wireguard tunnel between host and Linux guest in Qemu
#
# Run this script in one host shell via 'make run/wg_linux' from within your
# 'x86_64' build directory. The guest Linux shell comes up (you can exit this
# via ctrl+a).
# You can check the wireguard configurations via 'wg' at the host and in the guest.
# Doing 'ping 10.0.9.2' should now yield something like:
# '64 bytes from 10.0.9.2: icmp_seq=1 ttl=64 time=43.4 ms'.
#

assert_spec x86_64

source ${genode_dir}/repos/dde_linux/run/wireguard.inc

build "wg_linux wg_busybox"

wireguard_start

eval spawn qemu-system-x86_64 \
	-no-kvm -display sdl -nographic -serial mon:stdio -m 512 \
	-netdev tap,id=net0,ifname=tap0,script=no,downscript=no \
	-net nic,model=e1000,netdev=net0 \
	-object filter-dump,id=f1,netdev=net0,file=/tmp/dump.dat \
	-kernel wg_linux/arch/x86_64/boot/bzImage \
	-initrd wg_busybox/initramfs.cpio.gz \
	-append \"console=ttyS0 ip=dhcp\"

set timeout -1

interact {
	\001 {
		send_user "Expect: 'interact' received 'strg+A' and was cancelled\n";
		wireguard_exit
		exit
	}
}

