#
# Wireguard tunnel between host and Linux guest in Qemu
#
# Run this script in one host shell via 'make run/wg_linux' from within your
# 'x86_64' build directory. The guest Linux shell comes up (you can exit this
# via ctrl+a).
# From another host shell do 'make wg_init' from within the same build
# directory (can be undone via 'make wg_reset'). You can check the wireguard
# configurations via 'wg' at the host and in the guest. Doing 'ping 10.0.9.2'
# in the second host shell should now yield something like
# '64 bytes from 10.0.9.2: icmp_seq=1 ttl=64 time=43.4 ms'.
#

assert_spec x86_64

build "wg_linux wg_busybox"

eval spawn qemu-system-x86_64 \
	-no-kvm -display sdl -nographic -serial mon:stdio -m 512 \
	-netdev user,id=net0,hostfwd=udp::55552-:55552 \
	-net nic,model=e1000,netdev=net0 \
	-object filter-dump,id=f1,netdev=net0,file=/tmp/dump.dat \
	-kernel wg_linux/arch/x86_64/boot/bzImage \
	-initrd wg_busybox/initramfs.cpio.gz \
	-append \"console=ttyS0 ip=dhcp\"

set qemu_spawn_id $spawn_id
set timeout -1
interact {
	\001 {
		send_user "Expect: 'interact' received 'strg+A' and was cancelled\n";
		exit
	}
	-i $qemu_spawn_id
}
