build { core init vinit test/vinit }

create_boot_directory

install_config {
<config verbose="no">
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="CAP"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="IO_MEM"/>
		<service name="IRQ"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
	</parent-provides>
	<default-route><any-service><parent/></any-service></default-route>

	<start name="vinit">
		<resource name="RAM" quantum="40M"/>
		<config verbose="no">
			<parent-provides>
				<service name="ROM"/>
				<service name="RAM"/>
				<service name="CAP"/>
				<service name="PD"/>
				<service name="RM"/>
				<service name="CPU"/>
				<service name="IO_MEM"/>
				<service name="IRQ"/>
				<service name="LOG"/>
				<service name="SIGNAL"/>
			</parent-provides>
			<default-route><any-service><parent/></any-service></default-route>

			<emulator name="fpu">
				<binary name="test-vinit-fpu"/>
				<resource name="RAM" quantum="2M"/>
			</emulator>

			<emulated by="fpu">
				<resource name="IO_MEM" base="0x71000000" size="0x1000" local="0x0"/>
				<resource name="IO_MEM" base="0x71001000" size="0x1000" local="0x1000"/>
				<resource name="IRQ" base="2000" size="1" local="1"/>
			</emulated>

			<start name="test_1">
				<binary name="test-vinit"/>
				<resource name="RAM" quantum="3M"/>
			</start>

			<start name="test_2">
				<binary name="test-vinit"/>
				<resource name="RAM" quantum="3M"/>
			</start>

		</config>
	</start>

</config>
}

build_boot_image { core init vinit test-vinit-fpu test-vinit }

if {[have_spec hw_vea9x4] || [have_spec hw_pbxa9]} {
	run_genode_until forever
}

