#
# \brief  Virtual-machine monitor demo
# \author Stefan Kalkowski
# \date   2012-06-25
#

build "core init server/vmm test/mini_kernel hello drivers/timer"
create_boot_directory

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="CAP"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="VM"/>
	</parent-provides>
	<default-route>
		<any-service><any-child/><parent/></any-service>
	</default-route>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="vmm">
		<resource name="RAM" quantum="1M"/>
		<config image="mini_kernel">
			<memory>
				<region name="mainmem" start="0x60000000" size="0x20000000" />
				<region name="uart3"   start="0x1000c000" size="0x1000"/>
			</memory>
			<interrupts>
				<irq name="uart3" number="40"/>
			</interrupts>
		</config>
	</start>

	<start name="hello_server">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Hello"/></provides>
	</start>
	<start name="hello_client">
		<resource name="RAM" quantum="1M"/>
	</start>
</config>
}

build_boot_image "core init vmm mini_kernel hello_client hello_server timer"

append qemu_args " -m 64 -nographic"

# Execute the test in qemu if the targeted platform is supported
if {[have_spec hw_vea9x4] || [have_spec hw_pbxa9]} {
	run_genode_until "No children to start.*\n" 10
}
