#
# \brief  Virtual-machine monitor demo
# \author Stefan Kalkowski
# \date   2012-06-25
#

build "core init server/vmm"
create_boot_directory

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="CAP"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>
	<default-route><any-service><parent/></any-service></default-route>

	<start name="vmm">
		<resource name="RAM" quantum="2M"/>
	</start>

</config>
}

build_boot_image "core init vmm"

append qemu_args " -m 64 -nographic"

# Execute the test in qemu if the targeted platform is supported
if {[have_spec hw_vea9x4] || [have_spec hw_pbxa9]} {
	run_genode_until "No children to start.*\n" 10
}
