
assert_spec linux
assert_spec x86_64

exec rm -rf var/libcache/cbe
exec rm -rf var/libcache/cbe_cxx
exec rm -rf var/libcache/cbe_common
exec rm -rf var/libcache/cbe_common_cxx
exec rm -rf var/libcache/cbe_init
exec rm -rf var/libcache/cbe_init_cxx
exec rm -rf var/libcache/cbe_check
exec rm -rf var/libcache/cbe_check_cxx
exec rm -rf var/libcache/cbe_dump
exec rm -rf var/libcache/cbe_dump_cxx

set dd [installed_command dd]

proc cbe_image_name { } {
	return "cbe_block.img"
}

proc local_cbe_image { } {
	return bin/[cbe_image_name]
}

proc autopilot_cbe_image { } {
	return /tmp/[cbe_image_name].[exec id -un]
}

set image_size 256
if {[info exists ::env(CBE_IMAGE_SIZE)]} {
	set image_size $::env(CBE_IMAGE_SIZE)
}

proc cbe_image_size_mb { } {
	global image_size
	return $image_size
}

proc cbe_vbd_size_mb { } {
	return [expr [cbe_image_size_mb] / 2]
}

proc cbe_ft_size_mb { } {
	return [expr [cbe_image_size_mb] / 8]
}

append build_components {
	core
	init
	timer
	server/vfs
	app/cbe_tester
	server/log_terminal
	server/report_rom
	server/lx_fs
	server/lx_block
	lib/vfs_cbe_crypto_aes_cbc
	lib/vfs_cbe_trust_anchor
	lib/vfs_import
	lib/vfs_jitterentropy
}

build $build_components

create_boot_directory

append config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>

	<default caps="100"/>
	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="report_rom">
		<resource name="RAM" quantum="32M"/>
		<provides> <service name="Report"/> <service name="ROM"/> </provides>
		<config verbose="yes"/>
	</start>

	<start name="log_terminal">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Terminal"/></provides>
	</start>

	<start name="lx_fs" ld="no">
		<resource name="RAM" quantum="4M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<default-policy root="/" writeable="yes"/>
		</config>
	</start>

	<start name="lx_block" ld="no">
		<resource name="RAM" quantum="2M"/>
		<provides> <service name="Block"/> </provides>
		<config file="} [cbe_image_name] {" block_size="4K" writeable="yes"/>
	</start>

	<start name="vfs_trust_anchor" caps="120">
		<binary name="vfs"/>
		<resource name="RAM" quantum="16M"/>
		<provides><service name="File_system"/></provides>
		<config>
			<vfs>
				<dir name="storage">
					<ram/>
				</dir>

				<dir name="dev">
					<inline name="jitterentropy">0123456789abcdefghijklmnopqrstuv</inline>
					<cbe_trust_anchor name="cbe_trust_anchor"
					                  storage_dir="/storage"/>
				</dir>
			</vfs>

			<default-policy root="/dev/cbe_trust_anchor" writeable="yes"/>
		</config>
		<route>
			<service name="File_system"> <child name="lx_fs"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="test" caps="200">

		<binary name="cbe_tester"/>
		<resource name="RAM" quantum="80M"/>
		<config>

			<verbose
				cmd_pool_cmd_pending="no"
				cmd_pool_cmd_in_progress="no"
				cmd_pool_cmd_completed="no"
				blk_io_req_in_progress="no"
				blk_io_req_completed="no"
				ta_req_in_progress="no"
				ta_req_completed="no"
				crypto_req_completed="no"
				crypto_req_in_progress="no"
				client_data_mismatch="yes"
				client_data_transferred="no"/>

			<block-io type="vfs" path="/} [cbe_image_name] {"/>
			<crypto path="/crypto"/>
			<trust-anchor path="/trust_anchor"/>

			<vfs>
				<fs buffer_size="1M"/>
				<cbe_crypto_aes_cbc name="crypto"/>
				<dir name="trust_anchor">
					<fs label="trust_anchor"/>
				</dir>
			</vfs>

				<commands>

					<log string="Step 1: Initialize Trust Anchor and Tresor device, start Tresor library"/>

					<trust-anchor op="initialize" passphrase="foobar"/>
					<initialize>

						<virtual-block-device
							nr_of_levels="3"
							nr_of_children="3"
							nr_of_leafs="9" />

						<free-tree
							nr_of_levels="3"
							nr_of_children="4"
							nr_of_leafs="11" />

					</initialize>
					<construct/>

					<log string="Step 10: test synchronous rekeying"/>

					<request op="write" vba="20" count="1"  sync="yes"/>
					<request op="create_snapshot"           sync="yes"/>
					<request op="write" vba="33" count="1"  sync="yes"/>
					<request op="rekey"                     sync="yes"/>
					<request op="create_snapshot"           sync="yes"/>
					<request op="sync"  vba="0"  count="64" sync="yes"/>
					<check/>


				</commands>

		</config>

		<route>
			<service name="File_system" label_last="trust_anchor">
				<child name="vfs_trust_anchor"/>
			</service>
			<service name="File_system"> <child name="lx_fs"/> </service>
			<service name="Block"> <child name="lx_block"/> </service>
			<service name="Terminal"> <child name="log_terminal"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<any-service> <parent/> </any-service>
		</route>

	</start>

</config>}

install_config $config

exec rm -rf [local_cbe_image]
if { [get_cmd_switch --autopilot] } {

	exec rm -rf [autopilot_cbe_image]
	catch { exec $dd if=/dev/urandom of=[autopilot_cbe_image] bs=1M count=[cbe_image_size_mb] }
	exec ln -sf -T [autopilot_cbe_image] [local_cbe_image]

} else {

	catch { exec $dd if=/dev/urandom of=[local_cbe_image] bs=1M count=[cbe_image_size_mb] }
}

append boot_modules {
	core
	init
	timer
	cbe_tester
	ld.lib.so spark.lib.so
	libsparkcrypto.lib.so
	cbe_cxx.lib.so
	cbe_check_cxx.lib.so
	cbe_dump_cxx.lib.so
	cbe_init_cxx.lib.so
	log_terminal
	report_rom
	lx_fs
	vfs
	lx_block
	libc.lib.so
	libcrypto.lib.so
	vfs.lib.so
	vfs_cbe_trust_anchor.lib.so
	vfs_cbe_crypto_aes_cbc.lib.so
	vfs_import.lib.so
	vfs_jitterentropy.lib.so
}

append boot_modules [cbe_image_name]

build_boot_image $boot_modules

append qemu_args " -nographic -m 512 "

run_genode_until "child \"test\" exited with exit value.*\n" 360

if { [get_cmd_switch --autopilot] } {

	exec rm -rf [local_cbe_image]
	exec rm -rf [autopilot_cbe_image]
}

grep_output {\[init\] child "test" exited with exit value}
compare_output_to {[init] child "test" exited with exit value 0}
