create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/pkg/[drivers_interactive_pkg] \
                  [depot_user]/pkg/fonts_fs \
                  [depot_user]/src/init \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/nitpicker \
                  [depot_user]/src/libc \
                  [depot_user]/src/libpng \
                  [depot_user]/src/zlib \
                  [depot_user]/src/vfs_import \
                  [depot_user]/src/fs_query \
                  [depot_user]/src/menu_view \
                  [depot_user]/src/pointer \
                  [depot_user]/src/cbe \
                  [depot_user]/src/spark \
                  [depot_user]/src/libsparkcrypto \
                  [depot_user]/src/vfs_block \
                  [depot_user]/src/vfs \
                  [depot_user]/src/openssl \
                  [depot_user]/src/fs_tool \
                  [depot_user]/src/sandbox

build {
	app/cbe_manager
	app/cbe_init_trust_anchor
}

install_config {
	<config>

		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
		</parent-provides>

		<start name="timer" caps="100">
			<resource name="RAM" quantum="1M"/>
			<provides> <service name="Timer"/> </provides>
			<route>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="drivers" caps="1500" managing_system="yes">
			<resource name="RAM" quantum="64M"/>
			<binary name="init"/>
			<route>
				<service name="Timer">              <child name="timer"/> </service>
				<service name="Capture">            <child name="nitpicker"/> </service>
				<service name="Event">              <child name="nitpicker"/> </service>
				<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
				<service name="PD">                 <parent/> </service>
				<service name="ROM">                <parent/> </service>
				<service name="LOG">                <parent/> </service>
				<service name="CPU">                <parent/> </service>
				<service name="RM">                 <parent/> </service>
				<service name="IO_MEM">             <parent/> </service>
				<service name="IO_PORT">            <parent/> </service>
				<service name="IRQ">                <parent/> </service>
			</route>
		</start>

		<start name="report_rom" caps="100">
			<resource name="RAM" quantum="1M"/>
			<provides>
				<service name="Report"/>
				<service name="ROM"/>
			</provides>
			<config>
				<policy label="cbe_manager -> hover" report="nitpicker -> hover"/>
				<policy label="cbe_manager -> clipboard" report="cbe_manager -> clipboard"/>
			</config>
			<route>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="nitpicker" caps="100">
			<resource name="RAM" quantum="4M"/>
			<provides>
				<service name="Gui"/> <service name="Capture"/> <service name="Event"/>
			</provides>
			<config focus="rom">
				<capture/> <event/>
				<report hover="yes"/>
				<background color="#123456"/>
				<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
				<domain name="default" layer="3" content="client" label="no" hover="always" />
				<domain name="second" layer="2" xpos="200" ypos="300" content="client" label="no" hover="always" />

				<policy label_prefix="pointer" domain="pointer"/>
				<policy label_prefix="text_area.2" domain="second"/>
				<default-policy domain="default"/>
			</config>
			<route>
				<service name="Report"> <child name="report_rom" /> </service>
				<service name="Timer">  <child name="timer" /> </service>
				<service name="PD">     <parent/> </service>
				<service name="ROM">    <parent/> </service>
				<service name="LOG">    <parent/> </service>
				<service name="CPU">    <parent/> </service>
			</route>
		</start>

		<start name="pointer" caps="100">
			<resource name="RAM" quantum="1M"/>
			<route>
				<service name="Gui"> <child name="nitpicker" /> </service>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="cbe_fs" caps="100">
			<binary name="vfs"/>
			<resource name="RAM" quantum="100M"/>
			<provides><service name="File_system"/></provides>
			<config>
				<vfs>
					<dir name="cbe">
						<ram/>
					</dir>
					<dir name="dev">
						<cbe_trust_anchor name="cbe_trust_anchor"
						                  storage_dir="/cbe"/>
					</dir>
				</vfs>
				<policy label="cbe_manager -> cbe" root="/cbe" writeable="yes"/>
				<policy label="cbe_manager -> fs_query -> " root="/cbe" writeable="yes"/>
				<policy label="cbe_manager -> vfs_block -> " root="/cbe" writeable="yes"/>
				<policy label="cbe_manager -> cbe_init_trust_anchor -> trust_anchor" root="/dev/cbe_trust_anchor" writeable="yes"/>
				<policy label="cbe_manager -> cbe_init -> trust_anchor" root="/dev/cbe_trust_anchor" writeable="yes"/>
				<policy label="cbe_manager -> vfs -> trust_anchor" root="/dev/cbe_trust_anchor" writeable="yes"/>
				<policy label="cbe_manager -> vfs -> cbe_fs" root="/cbe" writeable="yes"/>
			</config>
			<route>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="fonts_fs" caps="150">
			<binary name="vfs"/>
			<resource name="RAM" quantum="4M"/>
			<provides>
				<service name="File_system"/>
			</provides>
			<config>
				<vfs>
					<rom name="Vera.ttf"/>
					<rom name="VeraMono.ttf"/>
					<dir name="fonts">
						<dir name="title">
							<ttf name="regular" path="/Vera.ttf" size_px="18" cache="256K"/>
						</dir>
						<dir name="text">
							<ttf name="regular" path="/Vera.ttf" size_px="14" cache="256K"/>
						</dir>
						<dir name="annotation">
							<ttf name="regular" path="/Vera.ttf" size_px="11" cache="256K"/>
						</dir>
						<dir name="monospace">
							<ttf name="regular" path="/VeraMono.ttf" size_px="14" cache="256K"/>
						</dir>
					</dir>
				</vfs>

				<policy label="cbe_manager -> menu_view -> fonts" root="/fonts" />
			</config>
			<route>
				<service name="ROM" label="config"> <parent label="fonts_fs.config"/> </service>
				<service name="PD">                 <parent/> </service>
				<service name="ROM">                <parent/> </service>
				<service name="LOG">                <parent/> </service>
				<service name="CPU">                <parent/> </service>
			</route>
		</start>

		<start name="data_fs" caps="300">
			<binary name="vfs"/>
			<resource name="RAM" quantum="8M"/>
			<provides>
				<service name="File_system"/>
			</provides>
			<config>
				<vfs>
					<ram/>
					<import>
						<rom name="drivers.config" binary="no"/>
					</import>
				</vfs>
				<default-policy root="/" writeable="yes"/>
			</config>
			<route>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="cbe_manager" caps="1000">
			<resource name="RAM" quantum="100M"/>
			<config>
				<report saved="yes"/>
				<save version="1"/>
				<vfs>
					<dir name="cbe">
						<fs label="cbe"/>
					</dir>
				</vfs>
			</config>
			<route>
				<service name="ROM"         label="clipboard">                             <child name="report_rom"/> </service>
				<service name="ROM"         label="hover">                                 <child name="report_rom"/> </service>
				<service name="File_system" label="menu_view -> fonts">                    <child name="fonts_fs"/> </service>
				<service name="File_system" label="cbe_init_trust_anchor -> trust_anchor"> <child name="cbe_fs"/> </service>
				<service name="File_system" label="cbe_init -> trust_anchor">              <child name="cbe_fs"/> </service>
				<service name="File_system" label="vfs_block -> ">                         <child name="cbe_fs"/> </service>
				<service name="File_system" label="cbe">                                   <child name="cbe_fs"/> </service>
				<service name="File_system" label="fs_query -> ">                          <child name="cbe_fs"/> </service>
				<service name="File_system" label="vfs -> cbe_fs">                         <child name="cbe_fs"/> </service>
				<service name="File_system" label="vfs -> trust_anchor">                   <child name="cbe_fs"/> </service>
				<service name="Report">                                                    <child name="report_rom"/> </service>
				<service name="Timer">                                                     <child name="timer"/> </service>
				<service name="Gui">                                                       <child name="nitpicker"/> </service>
				<service name="PD">                                                        <parent/> </service>
				<service name="ROM">                                                       <parent/> </service>
				<service name="CPU">                                                       <parent/> </service>
				<service name="LOG">                                                       <parent/> </service>
			</route>
		</start>

	</config>
}

set fd [open [run_dir]/genode/focus w]
puts $fd "<focus label=\"cbe_manager -> \"/>"
close $fd

build_boot_image {
	cbe_init_trust_anchor
	cbe_manager
}

run_genode_until forever
