assert_spec x86_64
assert_spec linux

build { app/file_vault app/file_vault_23_04 app/window_layouter app/decorator server/nitpicker server/wm }

create_boot_directory

append archives "
	[depot_user]/src/[base_src]
	[depot_user]/src/init
	[depot_user]/src/libc
	[depot_user]/src/zlib
	[depot_user]/src/fs_query
	[depot_user]/src/tresor
	[depot_user]/src/vfs_block
	[depot_user]/src/vfs
	[depot_user]/src/openssl
	[depot_user]/pkg/motif_wm
	[depot_user]/src/fs_tool
	[depot_user]/src/fs_utils
	[depot_user]/src/posix
	[depot_user]/src/rump
	[depot_user]/src/sandbox
	[depot_user]/src/nitpicker
	[depot_user]/src/menu_view
	[depot_user]/src/libpng
	[depot_user]/src/black_hole
	[depot_user]/src/report_rom
	[depot_user]/pkg/fonts_fs
	[depot_user]/pkg/system_shell
	[depot_user]/pkg/[drivers_interactive_pkg]
	[depot_user]/src/cbe
	[depot_user]/src/spark
	[depot_user]/src/libsparkcrypto
	[depot_user]/src/vfs_jitterentropy
	[depot_user]/src/lx_fs
	[depot_user]/src/vfs_jitterentropy
"

import_from_depot $archives

append config {

	<config>

		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
		</parent-provides>

		<start name="timer" caps="200">
			<resource name="RAM" quantum="1M"/>
			<resource name="CPU" quantum="5"/>
			<provides> <service name="Timer"/> </provides>
			<route>
				<service name="PD">      <parent/> </service>
				<service name="ROM">     <parent/> </service>
				<service name="LOG">     <parent/> </service>
				<service name="CPU">     <parent/> </service>
				<service name="IO_PORT"> <parent/> </service>
				<service name="IRQ">     <parent/> </service>
			</route>
		</start>

		<start name="drivers" caps="1500" managing_system="yes">
			<resource name="RAM" quantum="64M"/>
			<binary name="init"/>
			<route>
				<service name="Timer">              <child name="timer"/> </service>
				<service name="Capture">            <child name="nitpicker"/> </service>
				<service name="Event">              <child name="nitpicker"/> </service>
				<service name="ROM" label="config"> <parent label="drivers.config"/> </service>
				<service name="PD">                 <parent/> </service>
				<service name="ROM">                <parent/> </service>
				<service name="LOG">                <parent/> </service>
				<service name="CPU">                <parent/> </service>
				<service name="RM">                 <parent/> </service>
				<service name="IO_MEM">             <parent/> </service>
				<service name="IO_PORT">            <parent/> </service>
				<service name="IRQ">                <parent/> </service>
			</route>
		</start>

<start name="nitpicker" caps="100">
	<resource name="RAM" quantum="4M"/>
	<provides>
		<service name="Gui"/> <service name="Capture"/> <service name="Event"/>
	</provides>
	<config focus="rom">
		<capture/> <event/>

		<domain name="pointer" layer="1" content="client" label="no" origin="pointer" />
		<domain name="default" layer="2" content="client" label="no" hover="always"/>

		<policy label_prefix="pointer" domain="pointer"/>
		<default-policy domain="default"/>
	</config>
	<route>
		<service name="Timer"> <child name="timer"/> </service>
		<service name="PD">  <parent/> </service>
		<service name="ROM"> <parent/> </service>
		<service name="LOG"> <parent/> </service>
		<service name="CPU"> <parent/> </service>
	</route>
</start>

<start name="pointer" caps="100">
	<resource name="RAM" quantum="1M"/>
	<route>
		<service name="Gui"> <child name="nitpicker"/> </service>
		<any-service> <parent/> <any-child/> </any-service>
	</route>
</start>

<start name="wm" caps="1000">
	<resource name="RAM" quantum="32M"/>
	<binary name="init"/>
	<provides>
		<service name="Gui"/> <service name="Report"/> <service name="ROM"/>
	</provides>
	<route>
		<service name="ROM" label="config"> <parent label="wm.config"/> </service>
		<service name="Gui"> <child name="nitpicker"/> </service>
		<any-service> <parent/> <any-child/> </any-service>
	</route>
</start>

		<start name="fonts_fs" caps="150">
			<binary name="vfs"/>
			<resource name="RAM" quantum="4M"/>
			<provides>
				<service name="File_system"/>
			</provides>
			<config>
				<vfs>
					<rom name="Vera.ttf"/>
					<rom name="VeraMono.ttf"/>
					<dir name="fonts">
						<dir name="title">
							<ttf name="regular" path="/Vera.ttf" size_px="18" cache="256K"/>
						</dir>
						<dir name="text">
							<ttf name="regular" path="/Vera.ttf" size_px="14" cache="256K"/>
						</dir>
						<dir name="annotation">
							<ttf name="regular" path="/Vera.ttf" size_px="11" cache="256K"/>
						</dir>
						<dir name="monospace">
							<ttf name="regular" path="/VeraMono.ttf" size_px="14" cache="256K"/>
						</dir>
					</dir>
				</vfs>

				<policy label="terminal -> " root="/fonts" />
				<policy label="file_vault -> fonts" root="/fonts" />
				<policy label="file_vault_23_04 -> fonts" root="/fonts" />
			</config>
			<route>
				<service name="ROM" label="config"> <parent label="fonts_fs.config"/> </service>
				<service name="PD">                 <parent/> </service>
				<service name="ROM">                <parent/> </service>
				<service name="LOG">                <parent/> </service>
				<service name="CPU">                <parent/> </service>
			</route>
		</start>

		<start name="data_fs" caps="200" ld="no">
			<binary name="lx_fs"/>
			<resource name="RAM" quantum="4M"/>
			<provides>
				<service name="File_system"/>
			</provides>
			<config>
				<policy label="file_vault_23_04 -> data"
				        root="/file_vault_23_04_dir/data"
				        writeable="yes"/>

				<policy label="file_vault -> data"
				        root="/file_vault_dir/data"
				        writeable="yes"/>
			</config>
			<route>
				<service name="Timer"> <child name="timer"/> </service>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="trust_anchor_fs" caps="200" ld="no">
			<binary name="lx_fs"/>
			<resource name="RAM" quantum="4M"/>
			<provides>
				<service name="File_system"/>
			</provides>
			<config>
				<policy label="file_vault_23_04 -> trust_anchor"
				        root="/file_vault_23_04_dir/trust_anchor"
				        writeable="yes"/>


				<policy label="file_vault -> trust_anchor"
				        root="/file_vault_dir/trust_anchor"
				        writeable="yes"/>

			</config>
			<route>
				<service name="Timer"> <child name="timer"/> </service>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="file_vault" caps="2000">
			<resource name="RAM" quantum="200M"/>
			<config user_interface="menu_view" jitterentropy_available="yes">
				<vfs>
					<dir name="tresor">
						<fs label="tresor"/>
					</dir>
				</vfs>
			</config>
			<route>
				<service name="File_system" label="menu_view -> fonts">                  <child name="fonts_fs"        label="file_vault -> fonts"/> </service>
				<service name="Gui">                                                     <child name="wm"/> </service>
				<service name="File_system" label="tresor_trust_anchor_vfs -> storage_dir"> <child name="trust_anchor_fs" label="file_vault -> trust_anchor"/> </service>
				<service name="File_system" label="tresor_init -> ">                        <child name="data_fs"         label="file_vault -> data"/> </service>
				<service name="File_system" label="tresor">                                 <child name="data_fs"         label="file_vault -> data"/> </service>
				<service name="File_system" label="fs_query -> ">                        <child name="data_fs"         label="file_vault -> data"/> </service>
				<service name="File_system" label="image_fs_query -> ">                  <child name="data_fs"         label="file_vault -> data"/> </service>
				<service name="File_system" label="tresor_vfs -> tresor_fs">                   <child name="data_fs"         label="file_vault -> data"/> </service>
				<service name="File_system" label="truncate_file -> tresor">                <child name="data_fs"         label="file_vault -> data"/> </service>
				<service name="Timer">                                                   <child name="timer"/> </service>
				<service name="PD">                                                      <parent/> </service>
				<service name="ROM">                                                     <parent/> </service>
				<service name="CPU">                                                     <parent/> </service>
				<service name="LOG">                                                     <parent/> </service>
				<service name="RM">                                                      <parent/> </service>
			</route>
		</start>

		<start name="file_vault_23_04" caps="2000">
			<resource name="RAM" quantum="200M"/>
			<config>
				<vfs>
					<dir name="cbe">
						<fs label="cbe"/>
					</dir>
				</vfs>
			</config>
			<route>
				<service name="File_system" label="cbe_trust_anchor_vfs -> storage_dir"> <child name="trust_anchor_fs" label="file_vault_23_04 -> trust_anchor"/> </service>
				<service name="File_system" label="vfs_block -> ">                       <child name="data_fs"         label="file_vault_23_04 -> data"/> </service>
				<service name="File_system" label="cbe">                                 <child name="data_fs"         label="file_vault_23_04 -> data"/> </service>
				<service name="File_system" label="fs_query -> ">                        <child name="data_fs"         label="file_vault_23_04 -> data"/> </service>
				<service name="File_system" label="image_fs_query -> ">                  <child name="data_fs"         label="file_vault_23_04 -> data"/> </service>
				<service name="File_system" label="cbe_vfs -> cbe_fs">                   <child name="data_fs"         label="file_vault_23_04 -> data"/> </service>
				<service name="File_system" label="truncate_file -> cbe">                <child name="data_fs"         label="file_vault_23_04 -> data"/> </service>
				<service name="File_system" label="menu_view -> fonts">                  <child name="fonts_fs"        label="file_vault_23_04 -> fonts"/> </service>
				<service name="Timer">                                                   <child name="timer"/> </service>
				<service name="Gui">                                                     <child name="wm"/> </service>
				<service name="PD">                                                      <parent/> </service>
				<service name="ROM">                                                     <parent/> </service>
				<service name="CPU">                                                     <parent/> </service>
				<service name="LOG">                                                     <parent/> </service>
				<service name="RM">                                                      <parent/> </service>
			</route>
		</start>

	<start name="terminal" caps="150">
		<resource name="RAM" quantum="16M"/>
		<provides> <service name="Terminal"/> </provides>
		<config copy="yes" paste="yes">
			<initial width="800" height="600"/>
			<vfs> <dir name="fonts"> <fs/> </dir> </vfs>
		</config>
		<route>
			<service name="File_system"> <child name="fonts_fs"/> </service>
			<service name="Gui">         <child name="wm"/> </service>
			<service name="Report" label="clipboard"> <child name="report_rom"/> </service>
			<service name="ROM"    label="clipboard"> <child name="black_hole"/> </service>
				<service name="Timer"> <child name="timer"/> </service>
				<service name="PD">                                                      <parent/> </service>
				<service name="ROM">                                                     <parent/> </service>
				<service name="CPU">                                                     <parent/> </service>
				<service name="LOG">                                                     <parent/> </service>
				<service name="RM">                                                      <parent/> </service>
		</route>
	</start>

		<start name="report_rom" caps="100">
			<resource name="RAM" quantum="2M"/>
			<provides> <service name="ROM"/> <service name="Report"/> </provides>
			<config>
			</config>
<route>
				<service name="PD">                                                      <parent/> </service>
				<service name="ROM">                                                     <parent/> </service>
				<service name="CPU">                                                     <parent/> </service>
				<service name="LOG">                                                     <parent/> </service>
				<service name="RM">                                                      <parent/> </service>
</route>
		</start>

		<start name="black_hole" caps="100">
			<resource name="RAM" quantum="1280K"/>
			<provides>
				<service name="ROM"/>
			</provides>
			<config>
				<rom/>
			</config>
			<route>
				<service name="Timer"> <child name="timer"/> </service>
				<service name="ROM">   <parent/> </service>
				<service name="PD">    <parent/> </service>
				<service name="LOG">   <parent/> </service>
				<service name="CPU">   <parent/> </service>
			</route>
		</start>

	<start name="vfs" caps="150">
		<resource name="RAM" quantum="12M"/>
		<provides><service name="File_system"/></provides>
		<config>
			<vfs>
				<tar name="bash-minimal.tar" />
				<tar name="coreutils-minimal.tar" />
				<tar name="vim-minimal.tar" />
				<dir name="dev">
					<zero/> <null/> <terminal/>
					<inline name="rtc">2018-01-01 00:01</inline>
				</dir>
				<dir name="pipe"> <pipe/> </dir>
				<dir name="file_vault_23_04"> <fs label="file_vault_23_04"/> </dir>
				<dir name="file_vault">       <fs label="file_vault"      /> </dir>
				<dir name="tmp"> <ram /> </dir>
				<dir name="share"> <dir name="vim">
					<rom name="vimrc" binary="no"/>
				</dir> </dir>
			</vfs>

			<policy label_prefix="vfs_rom" root="/"/>
			<default-policy root="/" writeable="yes"/>
		</config>
		<route>
			<service name="File_system" label="file_vault_23_04"> <parent label="file_vault_23_04"/> </service>
			<service name="File_system" label="file_vault"      > <parent label="file_vault"/> </service>
			<service name="ROM" label="vimrc"> <parent label="vimrc"/> </service>
			<service name="Terminal"> <child name="terminal"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="vfs_rom" caps="100">
		<resource name="RAM" quantum="16M"/>
		<binary name="cached_fs_rom"/>
		<provides> <service name="ROM"/> </provides>
		<config/>
		<route>
			<service name="File_system"> <child name="vfs"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="/bin/bash" caps="450">
		<resource name="RAM" quantum="28M" />
		<exit propagate="yes"/>
		<config>
			<libc stdin="/dev/terminal" stdout="/dev/terminal"
			      stderr="/dev/terminal" rtc="/dev/rtc" pipe="/pipe"/>
			<vfs> <fs/> </vfs>
			<arg value="bash"/>
			<env key="TERM" value="screen"/>
			<env key="PATH" value="/bin" />
			<env key="PS1"  value="system:$PWD> " />
		</config>
		<route>
			<service name="File_system"> <child name="vfs"/> </service>
			<service name="ROM" label_suffix=".lib.so"> <parent/> </service>
			<service name="ROM" label_last="/bin/bash"> <child name="vfs_rom"/> </service>
			<service name="ROM" label_prefix="/bin">    <child name="vfs_rom"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>

	</config>
}

install_config $config

exec mkdir -p bin/file_vault_dir/data
exec mkdir -p bin/file_vault_dir/trust_anchor
exec mkdir -p bin/file_vault_23_04_dir/data
exec mkdir -p bin/file_vault_23_04_dir/trust_anchor

append boot_modules {
	file_vault
	file_vault-sync_to_tresor_vfs_init
	file_vault-truncate_file
	file_vault_dir
	file_vault_23_04
	file_vault_23_04-sync_to_cbe_vfs_init
	file_vault_23_04-truncate_file
	file_vault_23_04_dir
	window_layouter decorator nitpicker wm
}

#
# Pin the nitpicker focus to the window manager by providing a static focus ROM
#
set fd [open [run_dir]/genode/focus w]
puts $fd "<focus label=\"wm -> focus\"/>"
close $fd

copy_file [genode_dir]/repos/gems/recipes/raw/motif_wm/wm.config [run_dir]/genode/
copy_file [genode_dir]/repos/gems/run/sculpt/vimrc [run_dir]/genode/

append qemu_args " -display sdl "
build_boot_image $boot_modules
run_genode_until forever
