# riscv lacks jitterentropy support currently
if {[get_cmd_switch --autopilot] && [have_board virt_qemu_riscv]} {
	puts "Autopilot mode is not supported on this platform."
	exit 0
}

set dd [installed_command dd]

proc tresor_image_name { } {
	return "tresor_block.img"
}

proc lx_local_tresor_image { } {
	return bin/[tresor_image_name]
}

proc lx_autopilot_tresor_image { } {
	return /tmp/[tresor_image_name].[exec id -un]
}

proc lx_tresor_image_size_mb { } {
	return 400
}

proc benchmark_blk_count { } {

	if {[have_board linux]} {

		 # benchmarks over 50 mebibyte
		return 12800
	}
	if {[have_board virt_qemu_arm_v8a]} {

		# benchmarks over 25 mebibyte
		return 6400
	}
	# benchmarks turned off
	return 0
}

proc block_io_vfs_ram_mb { } {

	if {[benchmark_blk_count] > 0} {

		# when benchmarks turned on
		set bench_mb [expr (([benchmark_blk_count] * 4096) / 1024 / 1024)]
		return [expr 8 * $bench_mb]
	}
	# when benchmarks turned off
	return 10
}

proc jent_avail { } {

	if {[have_board pbxa9]} { return 0 }
	if {[have_board zynq_qemu]} { return 0 }
	return 1
}

append build_components {
	core
	init
	timer
	server/vfs
	app/tresor_tester
	server/log_terminal
	server/report_rom
	lib/vfs_tresor_crypto_aes_cbc
	lib/vfs_tresor_trust_anchor
	lib/vfs_import
}

append_if [jent_avail] build_components { lib/vfs_jitterentropy }

append_if [have_board linux] build_components { server/lx_fs }
append_if [have_board linux] build_components { server/lx_block }

build $build_components

create_boot_directory

append config {

	<config verbose="yes">

		<parent-provides>
			<service name="ROM"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
			<service name="PD"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="LOG"/>
		</parent-provides>

		<start name="timer" caps="100">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Timer"/></provides>
			<route>
				<service name="PD">      <parent/> </service>
				<service name="ROM">     <parent/> </service>
				<service name="LOG">     <parent/> </service>
				<service name="CPU">     <parent/> </service>
				<service name="IO_PORT"> <parent/> </service>
				<service name="IO_MEM">  <parent/> </service>
				<service name="IRQ">     <parent/> </service>
			</route>
		</start>

		<start name="report_rom" caps="100">
			<resource name="RAM" quantum="4M"/>
			<provides> <service name="Report"/> <service name="ROM"/> </provides>
			<config verbose="yes"/>
			<route>
				<service name="LOG"> <parent/> </service>
				<service name="PD">  <parent/> </service>
				<service name="CPU"> <parent/> </service>
				<service name="ROM"> <parent/> </service>
			</route>
		</start>

		<start name="log_terminal" caps="100">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Terminal"/></provides>
			<route>
				<service name="LOG"> <parent/> </service>
				<service name="PD">  <parent/> </service>
				<service name="CPU"> <parent/> </service>
				<service name="ROM"> <parent/> </service>
			</route>
		</start>
}
if {[have_board linux]} {

	append config {

		<start name="block_io_fs" caps="100" ld="no">
			<binary name="lx_fs"/>
			<resource name="RAM" quantum="4M"/>
			<provides> <service name="File_system"/> </provides>
			<config>
				<default-policy root="/" writeable="yes"/>
			</config>
			<route>
				<service name="LOG"> <parent/> </service>
				<service name="PD">  <parent/> </service>
				<service name="CPU"> <parent/> </service>
				<service name="ROM"> <parent/> </service>
			</route>
		</start>
	}

} else {

	append config {

		<start name="block_io_fs" caps="100">
			<binary name="vfs"/>
			<resource name="RAM" quantum="} [block_io_vfs_ram_mb] {M"/>
			<provides><service name="File_system"/></provides>
			<config>
				<vfs>
					<dir name="block_io">
						<ram/>
					</dir>
					<import>
						<dir name="block_io">
							<inline name="} [tresor_image_name] {"></inline>
						</dir>
					</import>
				</vfs>
				<default-policy root="/block_io" writeable="yes"/>
			</config>
			<route>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>
	}
}
append config {

		<start name="trust_anchor_fs" caps="200">
			<binary name="vfs"/>
			<resource name="RAM" quantum="10M"/>
			<provides><service name="File_system"/></provides>
			<config>
				<vfs>
					<dir name="storage">
						<ram/>
					</dir>

					<dir name="dev"> }

append_if [jent_avail] config {

						<jitterentropy name="jitterentropy"/> }

append_if [expr ![jent_avail]] config {

						<inline name="jitterentropy">0123456789abcdefghijklmnopqrstuv</inline> }

append config {
						<tresor_trust_anchor name="tresor_trust_anchor" storage_dir="/storage"/>
					</dir>
				</vfs>

				<default-policy root="/dev/tresor_trust_anchor" writeable="yes"/>
			</config>
			<route>
				<service name="PD">  <parent/> </service>
				<service name="ROM"> <parent/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="CPU"> <parent/> </service>
			</route>
		</start>

		<start name="test" caps="200">

			<binary name="tresor_tester"/>
			<resource name="RAM" quantum="10M"/>
			<config ld_verbose="yes">

				<verbose
					cmd_pool_cmd_pending="no"
					cmd_pool_cmd_in_progress="no"
					cmd_pool_cmd_completed="no"
					blk_io_req_in_progress="no"
					blk_io_req_completed="no"
					ta_req_in_progress="no"
					ta_req_completed="no"
					client_data_mismatch="yes"
					client_data_transferred="no"/>

				<block-io type="vfs" path="/} [tresor_image_name] {"/>
				<crypto path="/crypto"/>
				<trust-anchor path="/trust_anchor"/>

				<vfs>
					<fs buffer_size="1M"/>
					<tresor_crypto_aes_cbc name="crypto"/>
					<dir name="trust_anchor">
						<fs label="trust_anchor"/>
					</dir>
				</vfs>

				<commands>

					<log string="Step 1: Initialize Trust Anchor and Tresor device, start Tresor library"/>

					<trust-anchor op="initialize" passphrase="foobar"/>
					<initialize>

						<virtual-block-device
							nr_of_levels="3"
							nr_of_children="8"
							nr_of_leafs="64" />

						<free-tree
							nr_of_levels="3"
							nr_of_children="8"
							nr_of_leafs="64" />

					</initialize>
					<construct/>

					<log string="Step 10: test synchronous rekeying"/>

					<request op="write" vba="20" count="1"  sync="yes"/>
					<request op="create_snapshot"           sync="yes"/>
					<request op="write" vba="33" count="1"  sync="yes"/>
					<request op="rekey"                     sync="yes"/>
					<request op="create_snapshot"           sync="yes"/>
					<request op="sync"  vba="0"  count="64" sync="yes"/>
					<check/>


				</commands>

			</config>

			<route>
				<service name="File_system" label_last="trust_anchor"> <child name="trust_anchor_fs"/> </service>
				<service name="File_system"> <child name="block_io_fs"/> </service>
				<service name="Terminal"> <child name="log_terminal"/> </service>
				<service name="Timer"> <child name="timer"/> </service>
				<service name="LOG"> <parent/> </service>
				<service name="PD">  <parent/> </service>
				<service name="CPU"> <parent/> </service>
				<service name="ROM"> <parent/> </service>
			</route>

		</start>

	</config>
}

install_config $config

if {[have_board linux]} {

	exec rm -rf [lx_local_tresor_image]
	if { [get_cmd_switch --autopilot] } {

		exec rm -rf [lx_autopilot_tresor_image]
		catch { exec $dd if=/dev/urandom of=[lx_autopilot_tresor_image] bs=1M count=[lx_tresor_image_size_mb] }
		exec ln -sf -T [lx_autopilot_tresor_image] [lx_local_tresor_image]

	} else {

		catch { exec $dd if=/dev/urandom of=[lx_local_tresor_image] bs=1M count=[lx_tresor_image_size_mb] }
	}
}

append boot_modules {
	core
	init
	timer
	tresor_tester
	ld.lib.so
	log_terminal
	report_rom
	vfs
	libc.lib.so
	libcrypto.lib.so
	vfs.lib.so
	vfs_tresor_trust_anchor.lib.so
	vfs_tresor_crypto_aes_cbc.lib.so
	vfs_import.lib.so
}

append_if [jent_avail] boot_modules { vfs_jitterentropy.lib.so }

append_if [have_board linux] boot_modules { lx_fs }
append_if [have_board linux] boot_modules [tresor_image_name]

build_boot_image $boot_modules

append qemu_args " -nographic "

set test_timeout 100
if {[benchmark_blk_count] > 0} {
	set test_timeout 300
}
run_genode_until "child \"test\" exited with exit value.*\n" $test_timeout

if {[have_board linux]} {

	if { [get_cmd_switch --autopilot] } {

		exec rm -rf [lx_local_tresor_image]
		exec rm -rf [lx_autopilot_tresor_image]
	}
}

grep_output {\[init\] child "test" exited with exit value}
compare_output_to {[init] child "test" exited with exit value 0}
