create_boot_directory

import_from_depot \
	[depot_user]/src/[base_src] \
	[depot_user]/src/init \
	[depot_user]/src/report_rom \
	[depot_user]/src/vfs

install_config {
	<config>

		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
		</parent-provides>
		<default-route>
			<any-service> <parent/> <any-child/> </any-service>
		</default-route>
		<default caps="100"/>

		<start name="report_rom">
			<resource name="RAM" quantum="1M"/>
			<provides> <service name="Report"/> <service name="ROM"/> </provides>
			<config verbose="yes"/>
		</start>

		<start name="vfs_example_4" caps="120">
			<resource name="RAM" quantum="2M"/>
			<config>
				<vfs>
					<dir name="friendly">
						<inline name="greetings">Hello world!</inline>
					</dir>
					<dir name="dev"> <log/> </dir>
				</vfs>
				<libc stdout="/dev/log"/>
			</config>
		</start>

	</config>
}

append qemu_args " -nographic "

build { app/vfs_example_4 }

build_boot_image {

	vfs_example_4
	libc.lib.so
	libm.lib.so
	vfs.lib.so
	posix.lib.so
}

run_genode_until "exited with exit value 0" 30
