build { server/vfs lib/vfs/import test/libc }

create_boot_directory

import_from_depot \
	genodelabs/src/[base_src] \
	genodelabs/src/coreutils \
	genodelabs/src/init \
	genodelabs/src/libc \
	genodelabs/src/noux \
	genodelabs/src/posix \

install_config {
	<config verbose="yes">
		<parent-provides>
			<service name="ROM"/>
			<service name="LOG"/>
			<service name="RM"/>
			<service name="CPU"/>
			<service name="PD"/>
			<service name="IRQ"/>
			<service name="IO_MEM"/>
			<service name="IO_PORT"/>
		</parent-provides>
		<default-route>
			<any-service> <any-child/> <parent/> </any-service>
		</default-route>
		<default caps="100"/>
		<start name="timer">
			<resource name="RAM" quantum="1M"/>
			<provides><service name="Timer"/></provides>
		</start>
		<start name="noux" caps="500">
			<resource name="RAM" quantum="1G"/>
			<config stdin="/dev/null" stdout="/dev/log" stderr="/dev/log">
				<fstab>
					<dir name="dev"> <log/> <null/> </dir>
					<ram/>
					<import>
						<dir name="bin">
							<symlink name="sh" target="bash"/>
						</dir>
						<tar name="coreutils.tar" />
					</import>
				</fstab>
				<start name="/bin/ls"> <arg value="-Rla"/> </start>
			</config>
		</start>
	</config>
}

build_boot_image { vfs_import.lib.so libc.lib.so vfs vfs.lib.so }

append qemu_args " -nographic -serial mon:stdio "

run_genode_until {child "noux" exited.*\n} 30
