assert_spec linux

#
# Clean up Ada/SPARK remnants of previous builds
#
exec rm -rf var/libcache/cbe*

create_boot_directory

proc cbe_image_file { } {
	return "vfs_cbe_block.img"
}

proc cbe_image_size_mb { } {
	return 32
}

#
# Overwrite exit procedure to ensure to always remove the CBE image
#
rename exit run_tool_exit
proc exit {{status 0}} {
	exec rm -rf bin/[cbe_image_file]
	puts "rm -rf bin/[cbe_image_file]"
	run_tool_exit $status
}

build {
	core
	timer
	init
	server/lx_fs
	server/lx_block
	lib/vfs/cbe
	lib/vfs/cbe_crypto/aes_cbc
	lib/vfs/cbe_trust_anchor
	lib/vfs/pipe
	server/log_terminal
	server/fs_rom
	server/terminal
	server/vfs
	app/cbe_init
	app/cbe_init_trust_anchor
	app/sequence
	noux-pkg/coreutils
	noux-pkg/bash
}

append config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="RAM"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
		<service name="IO_PORT"/>
		<service name="PD"/>
		<service name="RM"/>
		<service name="CPU"/>
		<service name="LOG"/>
	</parent-provides>

	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="200"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides><service name="Timer"/></provides>
	</start>

	<start name="lx_block" ld="no">
		<resource name="RAM" quantum="2M"/>
		<provides> <service name="Block"/> </provides>
		<config file="} [cbe_image_file] {" block_size="4K" writeable="yes"/>
	</start>

	<start name="log_terminal">
		<resource name="RAM" quantum="2M"/>
		<provides><service name="Terminal"/></provides>
	</start>

	<start name="lx_fs" ld="no">
		<resource name="RAM" quantum="4M"/>
		<provides> <service name="File_system"/> </provides>
		<config> <default-policy root="/" writeable="yes"/> </config>
	</start>

	<start name="vfs_cbe_trust_anchor" caps="1000">
		<binary name="vfs"/>
		<resource name="RAM" quantum="16M"/>
		<provides><service name="File_system"/></provides>
		<config>
			<vfs>
				<dir name="ta_storage">
					<fs/>
				</dir>

				<dir name="dev">
					<cbe_trust_anchor name="cbe_trust_anchor"
					                  storage_dir="/ta_storage"/>
				</dir>
			</vfs>

			<default-policy root="/dev/cbe_trust_anchor" writeable="yes"/>
		</config>
		<route>
			<service name="File_system"> <child name="lx_fs"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

	<start name="sequence" caps="3000">
		<resource name="RAM" quantum="300M"/>
		<config>

			<start name="cbe_init_trust_anchor">
				<resource name="RAM" quantum="4M"/>
				<config passphrase="foobar" trust_anchor_dir="/trust_anchor">
					<vfs>
						<dir name="trust_anchor">
							<fs label="ta"/>
						</dir>
					</vfs>
				</config>
			</start>

			<start name="cbe_init">
				<resource name="RAM" quantum="4M"/>
				<config trust_anchor_dir="/trust_anchor">
					<vfs>
						<dir name="trust_anchor">
							<fs label="ta"/>
						</dir>
					</vfs>

					<key id="12"/>
					<virtual-block-device
						nr_of_levels="3"
						nr_of_children="64"
						nr_of_leafs="512" />

					<free-tree
						nr_of_levels="3"
						nr_of_children="64"
						nr_of_leafs="2048" />
				</config>
			</start>

			<start name="init" caps="1600">
				<resource name="RAM" quantum="256M"/>
				<config verbose="yes">

					<parent-provides>
						<service name="ROM"/>
						<service name="PD"/>
						<service name="RM"/>
						<service name="CPU"/>
						<service name="LOG"/>
						<service name="Timer"/>
						<service name="File_system"/>
						<service name="Terminal"/>
					</parent-provides>

					<default-route>
						<any-service> <parent/> </any-service>
					</default-route>
					<default caps="100"/>

					<start name="vfs_cbe" caps="200">
						<binary name="vfs"/>
						<resource name="RAM" quantum="16M"/>
						<provides><service name="File_system"/></provides>
						<config>
							<vfs>
								<fs buffer_size="1M" label="fs_backend"/>
								<cbe_crypto_aes_cbc name="cbe_crypto"/>
								<dir name="ta">
									<fs buffer_size="1M" label="ta"/>
								</dir>
								<dir name="dev">
									<cbe name="cbe" debug="no" verbose="yes"
										 block="/} [cbe_image_file] {"
										 crypto="/cbe_crypto"
										 trust_anchor="/ta"/>
								</dir>
							</vfs>

							<default-policy root="/dev" writeable="yes"/>
						</config>
						<route>
							<service name="File_system" label="fs_backend"> <parent label="fs"/> </service>
							<service name="File_system" label="ta">         <parent label="ta"/> </service>
							<any-service> <parent/> </any-service>
						</route>
					</start>

					<start name="vfs" caps="120">
						<resource name="RAM" quantum="30M"/>
						<provides><service name="File_system"/></provides>
						<config>
							<vfs>
								<tar name="coreutils.tar"/>
								<tar name="bash.tar"/>

								<dir name="home"> <ram/> </dir>
								<dir name="share"> </dir>
								<dir name="tmp"> <ram/> </dir>
								<dir name="dev">
									<zero/> <null/> <terminal/>
									<dir name="pipe"> <pipe/> </dir>
									<inline name="rtc">2018-01-01 00:01</inline>
								</dir>
							</vfs>

							<policy label_prefix="vfs_rom" root="/"/>
							<default-policy root="/" writeable="yes"/>
						</config>
						<route>
							<service name="Terminal"> <parent/> </service>
							<service name="Timer"> <child name="timer"/> </service>
							<any-service> <parent/> </any-service>
						</route>
					</start>

					<start name="fs_rom">
						<resource name="RAM" quantum="30M"/>
						<provides> <service name="ROM"/> </provides>
						<config/>
						<route>
							<service name="File_system"> <child name="vfs"/> </service>
							<any-service> <parent/> </any-service>
						</route>
					</start>

					<start name="/bin/bash" caps="1000">
						<resource name="RAM" quantum="64M"/>
						<config ld_verbose="yes">
							<libc stdin="/dev/terminal" stdout="/dev/terminal"
								  stderr="/dev/terminal" rtc="/dev/rtc" pipe="/dev/pipe"/>
							<vfs>
								<fs label="shell" buffer_size="1M"/>
								<dir name="dev">
									<fs label="cbe" buffer_size="1M"/>
								</dir>
								<dir name="share">
									<dir name="bash">
										<rom name="bashrc" label="vfs_cbe.sh"/>
									</dir>
								</dir>
							</vfs>
							<arg value="bash"/>
							<env key="TERM" value="screen"/>
							<env key="HOME" value="/"/>
							<env key="PATH" value="/bin"/>
						</config>
						<route>
							<service name="File_system" label="shell">  <child name="vfs"/> </service>
							<service name="File_system" label="cbe">    <child name="vfs_cbe"/> </service>
							<service name="ROM" label_suffix=".lib.so"> <parent/> </service>
							<service name="ROM" label_last="/bin/bash"> <child name="fs_rom"/> </service>
							<service name="ROM" label_prefix="/bin">    <child name="fs_rom"/> </service>
							<any-service> <parent/> <any-child/> </any-service>
						</route>
					</start>
				</config>
			</start>
		</config>
		<route>
			<service name="Terminal"> <child name="log_terminal"/> </service>
			<service name="File_system" label_last="fs"> <child name="lx_fs"/> </service>
			<service name="File_system" label_last="ta"> <child name="vfs_cbe_trust_anchor"/> </service>
			<service name="Timer"> <child name="timer"/> </service>
			<service name="Block"> <child name="lx_block"/> </service>
			<any-service> <parent/> </any-service>
		</route>
	</start>

</config>}

install_config $config

#
# Create empty image file that serves as CBE block back-end
#
exec rm -rf bin/[cbe_image_file]
exec truncate -s [cbe_image_size_mb]M bin/[cbe_image_file]

#
# Copy shell script for automated testing in bash to 'bin/'
#
set shell_script "run/vfs_cbe.sh"
set repo "[repository_contains $shell_script]"
exec cp $repo/$shell_script bin/

append boot_modules {
	lx_fs
	lx_block
	cbe_init
	cbe_init_cxx.lib.so
	cbe_init_trust_anchor
	spark.lib.so
	libsparkcrypto.lib.so
	cbe_cxx.lib.so
	vfs_cbe.lib.so
	vfs_cbe_crypto_aes_cbc.lib.so
	vfs_cbe_trust_anchor.lib.so
	vfs_cbe.sh
	vfs.lib.so
	vfs_pipe.lib.so
	vfs
	posix.lib.so
	libc.lib.so
	libm.lib.so
	libcrypto.lib.so
	log_terminal
	fs_rom
	sequence
	init
	core
	timer
	terminal
	bash.tar
	coreutils.tar
	ld.lib.so
	} [cbe_image_file] {
}

build_boot_image $boot_modules

run_genode_until {.*--- Automated CBE testing finished.*} 120
